ADD-APP_Routing
dkause/myflix-client pull request #4
Opened 2023-10-24 18:44 UTC by dkause

2023-10-24 21:49 UTC, stratospherique requested changes

2023-10-24 21:49 UTC, stratospherique commented on src/components/movie-view/movie-view.jsx
> +  const movie = movies.find((b) => b._id === movieId)
The error that you're getting is caused by the fact that the movie object is not getting properly extracted from the movies array(inside movie-view component). The movie variable here is getting undefined value instead of an object.

2023-10-24 21:49 UTC, stratospherique commented on src/components/movie-view/movie-view.jsx
> +  const movie = movies.find((b) => b._id === movieId)
Check this article to understand better the usage of `useParams`.https://www.telerik.com/blogs/how-to-use-3-popular-react-hooks-react-router#:~:text=The%20useParams()%20hook%20can,page%20is%20to%20be%20rendered.

Hint: the param was named `_id` in the main-view but referenced as `movieId`

2023-10-25 15:40 UTC, dkause commented on src/components/movie-view/movie-view.jsx
> +  const movie = movies.find((b) => b._id === movieId)
Thx, I fixed it.

2023-11-01 21:44 UTC, stratospherique requested changes

2023-11-01 21:44 UTC, stratospherique commented on src/components/favorite-button/favorite-button.jsx
> +}
Proptypes definition is missing. Kindly add it

2023-11-01 21:44 UTC, stratospherique commented on src/components/movie-card/movie-card.jsx
> +)
The synstax is incorrect because of the indentation. Besides, I don't see the need to have a `movies` props for this component.

The ideal way to determine if the movie is one of the users favorites is as follow:
`user.FavoriteMovies.include((movie._id)`

2023-11-02 21:01 UTC, stratospherique requested changes
Make sure the check the browser devtools -> console tab. You'll see runtime warnings & errors with debugging information.

2023-11-02 21:01 UTC, stratospherique commented on src/components/profile-view/profile-view.jsx
> +  const [Password, setPassword] = useState(user.Password)
This a dangerous practice. The password that you initially receive is hashed, when the user submits the form without changing the password input, he won't be able to recover his account. Kindly leave it empty until the user inserts it.

2023-11-05 23:19 UTC, stratospherique requested changes

2023-11-05 23:19 UTC, stratospherique commented on src/components/main-view/main-view.jsx
>          }}
`setToken(null)` is missing

2023-11-05 23:19 UTC, stratospherique commented on src/components/main-view/main-view.jsx
> +                        token={token}
Here you need to add the `setUser` prop that you intend to pass down to the favorite-button component(just like with `onLogout` function defined above)

2023-11-05 23:19 UTC, stratospherique commented on src/components/favorite-button/favorite-button.jsx
> +        .then((user) => setUser(user))
There is no need to add two extra `then` promise function. You can just call `setUser(responseUser)` in the previous then function.

2023-11-05 23:19 UTC, stratospherique commented on src/components/favorite-button/favorite-button.jsx
> +        }
`setUser` is missing Here

2023-11-05 23:19 UTC, stratospherique commented on src/components/favorite-button/favorite-button.jsx
> +          // You may want to update the user's favorite movies here
`return response.json()` is missing here. Otherwise, you get undefined data for the next then block.

2023-11-09 17:41 UTC, stratospherique requested changes

2023-11-09 17:41 UTC, stratospherique commented on src/components/profile-view/profile-view.jsx
> +      }
After a successful update, you need to update the `user` state variable of `main-view`. Since `setUser` is already passed to the component, you can use it here.

`return response.json()` and update the user in another `then` block.

2023-11-09 17:41 UTC, stratospherique commented on src/components/profile-view/profile-view.jsx
> +    <Row className="justify-content-md-center mt-3 p-5">
Not properly indenting the code makes it hard to debug it. Also, commented code affects the readability of the script.

2023-11-09 17:41 UTC, stratospherique commented on src/components/profile-view/profile-view.jsx
> +      }
Regardless, the update operation doesn't work from the API side, it must be something related to storing the encrypted version of the password.

2023-11-11 11:55 UTC, dkause commented on src/components/main-view/main-view.jsx
>          }}
Done

2023-11-11 11:56 UTC, dkause commented on src/components/profile-view/profile-view.jsx
> +    <Row className="justify-content-md-center mt-3 p-5">
Done

2023-11-16 16:36 UTC, merged